# syntax=docker/dockerfile:1.0-experimental
FROM  alpine:latest

LABEL MAINTAINER "louisehong <louisehong4168@gmail.com>"

ENTRYPOINT ["/usr/bin/kube-state-metrics", "--port=8080", "--telemetry-port=8081"]

USER nobody

ARG TARGETPLATFORM
WORKDIR /usr/bin

COPY kube-state-metrics kube-state-metrics

EXPOSE 8080 8081
