on:
  push:
    tags:
      - 'kube-state-metrics-v**' # Push events to matching v*, i.e. v1.0, v20.15.10

name: kube-state-metrics Release

jobs:

  build:
    name: Build Release Binaries
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.15.8'

      - name: Prepare
        id: prepare
        run: |
          RELEASEVER=${{ github.ref }}
          echo "::set-output name=tag_name::${RELEASEVER#refs/tags/kube-state-metrics-}"

      - name: Checkout kube-state-metrics
        uses: actions/checkout@v2
        with:
          repository: kubernetes/kube-state-metrics
          ref: ${{ steps.prepare.outputs.tag_name }}
          path: src/k8s.io/kube-state-metrics

      - name: set up buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: login to dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin


      - name: Get metrics
        run: |
          wget -c https://raw.githubusercontent.com/oldthreefeng/arm64-docker/main/kube-state-metrics/kube-metrics.yml
          wget -c https://raw.githubusercontent.com/oldthreefeng/arm64-docker/main/kube-state-metrics/Dockerfile.kube-metrics 
          cp kube-metrics.yml .goreleaser.yml
          cp Dockerfile.kube-metrics  Dockerfile.hub
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
          ./bin/goreleaser release --timeout=1h
        working-directory: src/k8s.io/kube-state-metrics

      - name: Save kube-state-metrics binaries
        uses: actions/upload-artifact@v2
        with:
          name: kube-state-metrics-binaries
          path: src/k8s.io/kube-state-metrics/dist/kube-state-metrics*.tar.gz


      # - name: build (and publish) main image
      #   env:
      #     # fork friendly ^^
      #     DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      #   run: |
      #     docker buildx build \
      #       --platform linux/amd64,linux/arm64 \
      #       --build-arg VERSION=${{ steps.prepare.outputs.tag_name }} \
      #       --push \
      #       -t ${DOCKER_REPO:-louisehong/kube-state-metrics}:${{ steps.prepare.outputs.tag_name }} \
      #       -t ${DOCKER_REPO:-louisehong/kube-state-metrics}:latest \
      #       -f Dockerfile.hub \
      #       .
      #   working-directory: src/k8s.io/kube-state-metrics